# Generated by Django 5.2.6 on 2025-11-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lore', models.TextField()),
                ('strength', models.IntegerField()),
                ('magic', models.IntegerField()),
            ],
        ),
    ]
