# Generated by Django 5.2.6 on 2025-12-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_skin_character_skin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skin',
            old_name='image',
            new_name='sprite',
        ),
        migrations.AlterField(
            model_name='skin',
            name='lore',
            field=models.TextField(),
        ),
    ]
